from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.database import get_db
from app.models.meal_plan import MealPlan
from app.models.user import User
from app.schemas.meal_plan import MealPlanRequest, MealPlanResponse
from app.auth.dependencies import get_current_user
from app.services.meal_planner import generate_meal_plan
from app.services.ai_service import get_user_health_context

router = APIRouter()

@router.post("/generate", response_model=MealPlanResponse)
async def create_meal_plan(
    req: MealPlanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Generates a new meal plan using AI and saves it."""
    health_context = await get_user_health_context(db, current_user)
    
    try:
        plan_data = await generate_meal_plan(
            health_context=health_context,
            preferences=req.preferences,
            num_meals=req.num_meals,
            user=current_user
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
        
    db_plan = MealPlan(
        user_id=current_user.id,
        preferences=req.preferences,
        plan_data=plan_data
    )
    db.add(db_plan)
    await db.commit()
    await db.refresh(db_plan)
    return db_plan

@router.get("/latest", response_model=MealPlanResponse)
async def get_latest_meal_plan(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Retrieves the most recent meal plan generated by the user."""
    result = await db.execute(
        select(MealPlan)
        .filter(MealPlan.user_id == current_user.id)
        .order_by(MealPlan.created_at.desc())
        .limit(1)
    )
    plan = result.scalars().first()
    if not plan:
        raise HTTPException(status_code=404, detail="No meal plans found")
    return plan
