"""add_user_ai_settings

Revision ID: 00a34ea76c45
Revises: 2026_06_07_0000
Create Date: 2026-06-07 21:27:34.967063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a34ea76c45'
down_revision: Union[str, None] = '2026_06_07_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('ai_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('ai_base_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_base_url')
    op.drop_column('users', 'ai_model')
    op.drop_column('users', 'ai_api_key')
    op.drop_column('users', 'ai_provider')
    # ### end Alembic commands ###

